font:
  enable: true
  global:
    size: 0.85

toc:
  enable: true
  expand_all: true
  max_depth: 5

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags

custom_file_path:
  style: styles.styl
