font:
  enable: true
  global:
    size: 0.85

toc:
  enable: true
  expand_all: true
  max_depth: 5

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  categories: /categories/ || fa fa-th

codeblock:
  copy_button:
    enable: true
    show_result: true

text_align:
  desktop: start
  mobile: start

custom_file_path:
  style: styles.styl
